name: 'CD Feature Plan certificazione'

on:
  workflow_dispatch:
  push:
    tags: [ "PLAN-CERTIFICAZIONE" ]

permissions:
  contents: write
  id-token: write
  checks: write
  pull-requests: write

jobs:
  plan:
    uses: itsiae/siae-gh-actions/.github/workflows/terragrunt-plan.yaml@v2.1.0
    name: 'Terragrunt Plan'
    secrets: inherit
    with:
      working_dir: live
      environment: certificazione

  tag-management:
    uses: itsiae/siae-gh-actions/.github/workflows/tagging-and-releasing-mgmt.yaml@v2.1.0
    name: 'Create Release'
    needs: [ plan ]
    secrets: inherit
